services:
  # PostgreSQL Database for LangGraph
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=langgraph
      - POSTGRES_USER=langgraph
      - POSTGRES_PASSWORD=langgraph
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langgraph"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for LangGraph task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LangGraph Backend
  langgraph-backend:
    build:
      context: ./examples/langgraph-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGGRAPH_DB_URL=postgresql://langgraph:langgraph@postgres:5432/langgraph
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    volumes:
      - ./examples/langgraph-backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SvelteKit Frontend
  svelte-frontend:
    build:
      context: .
      dockerfile: ./examples/dashboard/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUBLIC_LANGSERVE_CHATBOT_URL=http://langserve-backend:8000/chatbot
      - PUBLIC_LANGSERVE_CHATBOT_PERSISTENT_URL=http://langserve-backend:8000/chatbot-persistent
      - PUBLIC_LANGSERVE_CODE_URL=http://langserve-backend:8000/code-assistant
      - PUBLIC_LANGSERVE_DATA_URL=http://langserve-backend:8000/data-analyst
      - PUBLIC_LANGSERVE_CREATIVE_URL=http://langserve-backend:8000/creative-writer
      - PUBLIC_LANGSERVE_RESEARCH_URL=http://langserve-backend:8000/research-assistant
      - PUBLIC_SOCKET_IO_URL=http://localhost:3000
    depends_on:
      - langgraph-backend
    volumes:
      - ./examples/dashboard:/app
      - /app/node_modules
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - svelte-frontend
      - langgraph-backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: