import { compile } from 'json-schema-to-typescript';
import type { JSONSchema } from '../schema.js';

/**
 * Generate TypeScript type definitions from JSON schema
 */
export async function generateTypesFromSchema(schema: JSONSchema): Promise<string> {
  try {
    const types = await compile(schema, 'LangServeTypes', {
      bannerComment: '// Generated types for svelte-langserve\n// Do not edit this file directly',
      style: {
        semi: true,
        singleQuote: true,
        tabWidth: 2,
      },
    });
    
    return types;
  } catch (error) {
    throw new Error(`Failed to generate TypeScript types: ${error}`);
  }
}