name: Docker Bake

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - 'docker-bake.hcl'
      - '.github/workflows/docker-bake.yml'
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - 'docker-bake.hcl'
      - '.github/workflows/docker-bake.yml'

env:
  REGISTRY: ghcr.io
  REPO: synergyai-nl/svelte-langserve

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            TAG=latest
          else
            TAG=${{ github.sha }}
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
          targets: all
          push: false
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPO: ${{ env.REPO }}
          TAG: ${{ steps.meta.outputs.TAG }}